[package]
name = "list_all_files"
version = "0.1.0"
authors = ["Ivan Acosta-Rubio <ivan@softwarecriollo.com>"]
edition = "2018"

[dependencies]
rust-crypto = "^0.2"

aes-stream = "0.2.1"

rand = "0.6.5"

base64 = "0.10.1"
